name: Build Windows EXE

on:
  push:
    branches:
      - gui
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./fill-docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Build with PyInstaller
        run: uv run pyinstaller build.spec

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-EXE
          path: fill-docs/dist/fill-docs.exe
          retention-days: 5
